server:
  port: 8090
  error:
    include-stacktrace: on_param
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${HOST_DB:localhost:5432}/animes?ApplicationName=api-spring-essential
    username: ${DB_USER:postgres}
    password: ${DB_PW:postgres}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG